<section role="main" >



    <section class="panel">
        <div class="panel-body">
            <h3 class="mt-none">Terms of use agreement</h3>
            <p>
                This is a binding agreement ("Agreement") between <a href="orlounge.com">www.orlounge.com</a> and you ("You" or "your").
                This Agreement governs your use of <a href="#">www.orlounge.com</a>.
                These Terms and Conditions also apply to a member of the <a href="#">www.orlounge.com</a> Advisory Board.
                To the extent the Terms and Use conflict with the Terms and Conditions, the latter shall apply.
            </p>

            <p>
                <b>Description of Services</b><br/>
                This Site provides healthcare providers  with communication tools and member contributed resources and
                information (collectively the "Contents"), to participate in and manage professional communities.

            </p>
            <p>
                <b>Membership</b><br/>
                You represent and warrant that<br/>
                (a) all registration information you submit is truthful and accurate<br/>
                (b) you will maintain the accuracy of such information<br/>
                (c) you are a licensed healthcare provider; and <br/>
                (d) your use of the Site services does not violate any applicable law or regulation.<br/>

                Your profile may be deleted and your membership in the Site may be terminated without warning
                if we believe that you are not a licensed healthcare provider.


            </p>
            <p>
                <b>
                    Your registration information is accurate

                </b><br/>
                Your personal professional profile, including your credentials, education,
                professional experience and relevant background will be available for
                viewing by other registered members of the Site and will be considered non-confidential and non-proprietary.
                Your professional profile is like your telephone directory information which members can see.

            </p>

            <p>
                <b>
                    Ownership of Contents
                </b><br/>
                All Contents on the Site including the ORLOUNGE trademarks,
                service marks and logos contained therein are owned by or licensed to <a href="#">www.orlounge.com</a> and are subject
                to copyright and other intellectual property rights under United States and foreign laws and international
                conventions.
                <br/>
                You hereby grant to the Site a limited nonexclusive, worldwide, royalty-free,
                sublicensable (through multiple tiers)
                and transferable license to use, modify, publicly perform, publicly display,
                reproduce, edit, aggregate, translate, reformat, prepare derivative works based upon,
                distribute and otherwise exploit such Member Contents, in whole or in part, solely on and through the Site.<br/>


                <b>Your rights</b><br/>
                You are prohibited from posting or transmitting to or from this Site any unlawful,
                infringing, threatening, libelous, defamatory, obscene, pornographic, or other material that would violate any law.
                You are prohibited from revealing the name or other personally identifying information of any other
                Site member unless that individual has previously revealed his or her own name or personally identifying
                information in that specific Site post.
                <br/>
                Site Contents may not be copied, reproduced, distributed, transmitted, broadcast, displayed, sold,
                licensed, uploaded, or otherwise exploited without the prior written consent of the respective owners.

            </p>


            <p>
                <b>Disclaimers</b><br/>
                <b>General</b><br/>
                <b>ORLOUNGE</b> facilitates the exchange of ideas and information concerning the members work in the
                their professional sphere.
                Contents generated by the members are the responsibilities of the members.
                We make no representation or warranty, express or implied, that their contents are accurate of complete.
                All members are to follow strict <b>HIPPA</b> regulations.<br/>
                Paid advertising materials are provided by the respective owners, who shall be solely responsible for their contents.

                <br/>


                In particular, <b>ORLOUNGE.COM</b> shall not be liable for any loss or damage which may arise whether
                directly or indirectly from the use of any of the information on this website.<br/>
                The contents displayed or made available on the site are provided "as is" without any express or implied
                warranty of any kind, including warranties of merchantability, fitness for any particular purpose,
                warranties arising by course of dealing or custom or trade or non-infringement of intellectual property.
                In no event shall www.orlounge.com, its subsidiaries, directors, officers, employees or stockholders be
                liable to you or any other entity for any and all damages including but not limited to direct, compensatory,
                indirect, incidental, consequential, special, exemplary or punitive damages (including, without limitation,
                damages for loss of profits, business interruption, loss of information and loss of business opportunities) arising out of or relating to<br/>
                (1) the use of, or inability to use, the contents, or<br/>
                (2) reliance on the content and contents; or<br/>
                (3) errors, inaccuracies, omissions, defects, untimeliness, security breaches; or<br/>
                (4) information communicated through threaded online discussions, message boards or physician data rooms;<br/>
                (5) the satisfaction of any government regulation requiring disclosure of information on prescription or "off-label"
                uses of drugs or devices contained in site contents or<br/>
                (6) any other failure to perform by www.orlounge.com. or its content providers.<br/>
                The foregoing shall apply regardless of whether www.orlounge.com. has been advised of the possibility of such damages.<br/>
                www.orlounge.com makes no representations or warranties that your access to and use of the site, contents,
                or third party sites<br/>
                &nbsp;&nbsp;(1) will be uninterrupted or error-free;<br/>
                &nbsp;&nbsp;(2) is free of viruses, unauthorized code, or other harmful components,<br/>
                &nbsp;&nbsp;(3) is secure,<br/>
                &nbsp;&nbsp;(4) will meet your satisfaction.<br/>
            </p>

        </div>
    </section>

</section>
