<section role="main" width="" class="content-body">
    <header class="page-header" style="top:130px;">
        <h2>Copyright Notice & Disclaimer</h2>

        <div class="right-wrapper pull-right">
            <ol class="breadcrumbs">
                <li>
                    <a href="index.html">
                        <i class="fa fa-home"></i>
                    </a>
                </li>
                <li><span>Layouts</span></li>
                <li><span>Menu Collapsed</span></li>
            </ol>

            <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
        </div>
    </header>

    <h3 class="mt-none">Copyright Notice</h3>

    <section class="panel">
        <div class="panel-body">
            <p>
                <a href="www.orlounge.com">www.orlounge.com</a> is the sole owner of this website and its entire contents. Contents cannot be published for any commercial purpose.<br/>
                All logos, images, pictures, displayed on this site are the copyrights and trademarks of their respective owners and they retain the ownership and credit.<br/>
                Owners of material not wished displayed may contact us for immediate removal.

            </p>
        </div>
    </section>
    <h3 class="mt-none">Disclaimer</h3>

    <section class="panel">
        <div class="panel-body">
            <p>

                <b>ORLOUNGE</b> facilitates the exchange of ideas and information concerning their work in the their professional sphere. Contents generated by the members are the responsibilities of  the members. We make no representation or warranty, express or implied, that their contents are accurate of complete.<br/>
                All members are to follow strict HIPPA regulations.<br/>
                Paid advertising materials are provided by the respective owners, who shall be solely responsible for their contents.<br/>
                <b>ORLOUNGE.COM</b>  shall not be liable for any loss or damage which may arise whether directly or indirectly from the use of any of the information on this website.</br>


            </p>
        </div>
    </section>



</section>
